### ISSUE TITLE
why is the string `"null"` quoted?

### ISSUE THREAD

**Issue by chdsbd** [go-logfmt/logfmt#13]
I was wondering why the string `"null"` gets quoted. I would have expected it to be rendered as `k=null`.

https://github.com/go-logfmt/logfmt/blob/2fe45f2cf057d707c50bc1949e25ec2cd6b7a015/encode_test.go#L25

**Comment by ChrisHines** [comment]
Because unquoted `null` as in `k=null` is reserved to mean an empty value. See the test case a few lines higher, here:

https://github.com/go-logfmt/logfmt/blob/2fe45f2cf057d707c50bc1949e25ec2cd6b7a015/encode_test.go#L22

The quotes allow a decoder to tell the difference between an empty value and a literal string `"null"`.

**Comment by chdsbd** [comment]
Oh, that makes sense. Thanks for the quick response!
