### ISSUE TITLE
safeString() not so safe

### ISSUE THREAD

**Issue by bboreham** [go-logfmt/logfmt#6]
It handles a panic arising from attempting to print a null string, but if the stringer panics for some other reason it will re-throw the panic. For my purposes it would be better to note the panic in the log message and carry on.

I guess tastes vary, but it surprised me that there is a panic handler but only for one specific case.

**Comment by ChrisHines** [comment]
Good observation.

The basic structure of `safeString` was modeled on how the standard library `fmt` package handles panics. It's been a while since I implemented it here, and I haven't tracked if the `fmt` package's handling of panics has improved or changed since I looked at it back then, but here is the pertinent code in `fmt` today: https://golang.org/src/fmt/print.go#L530. At first glance it looks like `fmt` tries harder to avoid propagating the panic.

I tend to agree with your suggestion that we can and probably should do more here. Would you like to work on a PR to improve this?

**Comment by bboreham** [comment]
I took a look at `fmt/print.go`; it will take first the `%v` format string; if that panics and it was a null pointer then `<nil>`; otherwise try to print the panic value; if _that_ panics then it re-throws the panic.

I can get similar behaviour by writing `s, ok = fmt.Sprintf("PANIC:%v", panicVal), false` in the else clause of `safeString`.  Will try to do a PR with this today.

To what extent do you want the decode side to work with panic values?  Perhaps they should obviously fail to decode?

**Comment by ChrisHines** [comment]
That sounds like a reasonable approach to me. If you do submit a PR please make the same improvements to `safeError` and `safeMarshal` as well.

I don't think the decode side needs to do anything special. The decoder only returns `[]byte` data for the keys and values it parses. It doesn't interpret the keys or values in any way and I don't think it should start now.

**Comment by ChrisHines** [comment]
Yes, you did, and I totally lost track of that. My apologies.

I'll try to review that soon. I've also been thinking about another change to improve the way this package handles invalid keys. So I'd like to work on that and probably release it together with your improvements in v0.4.0.

**Comment by AlekSi** [comment]
Was it done? Can this issue be closed?

**Comment by ChrisHines** [comment]
Yes, it was done. #7 was merged. Don't know why the issue didn't get closed. Thanks for the reminder.
