### ISSUE TITLE
MarshalKeyvals doesn't work as expected

### ISSUE THREAD

**Issue by nergdron** [go-logfmt/logfmt#9]
either I'm misunderstanding the use of logfmt.MarshalKeyvals, or it doesn't work as expected. I'm doing the following:

```go
keyvals := []string{"app", "myapp", "env", "prod", "error", "errormsg"}
fmt.Println("keyvals:", keyvals)
out, err := logfmt.MarshalKeyvals(keyvals)
fmt.Println(string(out), err)
```
but instead of getting formatted output, I get:
```
keyvals: [app myapp env prod error errormsg]
 <nil>
```

so no output, and no error.

this is go version 1.14.5.

**Comment by ChrisHines** [comment]
The function signature of `MarshalKeyvals` is as follows.

```go
func MarshalKeyvals(keyvals ...interface{}) ([]byte, error)
```

That is, it accepts a variable number of `interface{}` arguments. It can be called in one of two ways.

Either explicitly listing a sequence of keys and values

```go
logfmt.MarshalKeyvals("app", "myapp", "env", "prod", "error", "errormsg")
```

Or expanding a pre-existing slice in place, like so.

```go
kvs := []interface{}{"app", "myapp", "env", "prod", "error", "errormsg"}
logfmt.MarshalKeyvals(kvs...)
```

(See also the section in the Go spec entitled [Passing arguments to ... parameters](https://golang.org/ref/spec#Passing_arguments_to_..._parameters).)

The code snippet you provided has two flaws that cause problems here.

First, the `...` is missing in the call to `MarshalKeyvals`. Without that `keyvals` is not expanded into the variadic parameter and instead is passed as a single argument. That is valid because any value, even a slice, can be converted to an `interface{}` value. The result is that `Keyvals` receives a single element slice with the only element containing your slice of strings. Instead of receiving six strings it receives `[]interface{}{keyvals}` or, expanding that, it receives `[]interface{}{[]string{"app", "myapp", "env", "prod", "error", "errormsg"}}`, a slice within a slice, which is not what you intended.

Note that this is the reason that you don't get any output. `MarshalKeyvals` is a helper function that is a thin wrapper around `Encoder.EncodeKeyvals`, which documents more details about its behavior. The docs for that method are:

>EncodeKeyvals writes the logfmt encoding of keyvals to the stream. Keyvals is a variadic sequence of alternating keys and values. Keys of unsupported type are skipped along with their corresponding value. Values of unsupported type or that cause a MarshalerError are replaced by their error but do not cause EncodeKeyvals to return an error. If a non-nil error is returned some key/value pairs may not have be written.

A `[]string` is an unsupported key type, and thus it is skipped. Since it is the only element of the `[]interface{}` Go creates to fill in the variadic parameter `MarshalKeyvals` returns an empty `[]byte`.

If we fix that problem by adding the `...` we discover the second problem. `keyvals := []string{"app", "myapp", "env", "prod", "error", "errormsg"}` is a slice of strings, and Go will not automatically convert a `[]string` to a `[]interface{}`. You can see the compiler error when you [run that version on the Go playground](https://play.golang.org/p/QvIm4eBjKJh). This is a commonly encountered issue and is covered in the Go FAQ entry [Can I convert a []T to an []interface{}?](https://golang.org/doc/faq#convert_slice_of_interface)

Changing the type of keyvals to a `[]interface{}` resolves this problem. [See this on the playground.](https://play.golang.org/p/8gBKzXzhISr)

I hope that helps.

**Comment by nergdron** [comment]
thanks, that's clear! appreciate the guidance!
